runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: "14"
        registry-url: "https://npm.pkg.github.com"
        scope: "@kungfu-trader"

    - name: Setup Yarn environment
      env:
        KF_SKIP_FALLBACK_BUILD: true
      shell: bash
      run: yarn --network-timeout=5000000 install --frozen-lockfile

    - name: Make libnode
      shell: bash
      # Workaround for gyp not able to find nasm.exe when run on GitHub Windows runner
      run: yarn make

    - name: Build
      env:
        KF_SKIP_MAKE_LIBNODE: true
      shell: bash
      run: yarn build

    - name: Package
      shell: bash
      run: yarn package

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        name: "libnode-${{env.BUILDER_OS}}-${{github.actor}}-${{github.sha}}"
        path: |
          **/build/stage/*/v*/v*/*.*
