runs:
  using: "composite"
  steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: "16"
        registry-url: "https://npm.pkg.github.com"
        scope: "@kungfu-trader"

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Setup Yarn environment
      run: yarn install
      shell: bash
      env:
        KF_SKIP_FALLBACK_BUILD: true

    - name: Make libnode
      # Workaround for gyp not able to find nasm.exe when run on GitHub Windows runner
      run: yarn make
      shell: bash

    - name: Build and Package
      run: |
        yarn build
        yarn package
      shell: bash
      env:
        KF_SKIP_MAKE_LIBNODE: true

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        name: "libnode-${{env.BUILDER_OS}}-${{github.actor}}-${{github.sha}}"
        path: |
          **/build/stage/*/v*/v*/*.*
        if-no-files-found: ignore
