name: Build
on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Type node version to build'
        required: true
        default: 'v14.18.0'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: "Linux"
            container: "docker.io/kungfutrader/kungfu-builder-centos:v1.1.1"
          - os: macos-11
            name: "MacOS"
          - os: windows-2019
            name: "Windows"
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    env:
      USE_HARD_LINKS: false
      BUILDER_OS: ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python environment
        if: matrix.name != 'Linux'
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup Windows environment
        if: matrix.name == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install -y nasm --no-progress

      - name: Setup Windows PATH for nasm
        if: matrix.name == 'Windows'
        run: |
          Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'NASM*')} | % { $_.FullName } | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
      
      - name: Build
        uses: ./.github/actions/builder
