name: Release - Verify
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - release/v*.x

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: "Linux"
          - os: macos-10.15
            name: "MacOS"
          - os: windows-2019
            name: "Windows"
    runs-on: ${{ matrix.os }}
    env:
      USE_HARD_LINKS: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
          scope: "@kungfu-trader"

      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Setup Windows environment
        if: ${{ matrix.name == 'Windows' }}
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install -y nasm --no-progress

      - name: Setup Windows PATH for nasm
        if: ${{ matrix.name == 'Windows' }}
        run: |
          Get-ChildItem -Path "${env:ProgramFiles}" | Where-Object {($_.Name -Like 'NASM*')} | % { $_.FullName } | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8
 
      - name: Setup Yarn environment
        run: yarn install
        env:
          KF_SKIP_FALLBACK_BUILD: true

      - name: Make libnode
        # Workaround for gyp not able to find nasm.exe when run on GitHub Windows runner
        run: yarn make

      - name: Build and Package
        run: |
          yarn build
          yarn package
        env:
          KF_SKIP_MAKE_LIBNODE: true

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          name: "libnode-${{matrix.name}}-${{github.actor}}-${{github.sha}}"
          path: |
            **/build/stage/*/v*/v*/*.*
          if-no-files-found: ignore

  release:
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: "github-artifacts"

      - name: Configure AWS Crendentials (US)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_US_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_US_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Stage Prebuilt to AWS (US)
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-path: "github-artifacts"
          bucket-staging: "kungfu-prebuilt-staging"
          no-comment: "true"

      - name: Configure AWS Crendentials (CN)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CN_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CN_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Stage Prebuilt to AWS (CN)
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts-path: "github-artifacts"
          bucket-staging: "kungfu-prebuilt-staging"
