name: Release - New Version
on:
  pull_request:
    types: [closed]
    branches:
      - release/v*.x

jobs:
  release:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
          scope: "@kungfu-trader"

      - name: Configure AWS Crendentials (US)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_US_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_US_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Publish Prebuilt to AWS (US)
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bucket-staging: 'kungfu-prebuilt-staging'
          bucket-release: 'kungfu-prebuilt'
          no-comment: "true"

      - name: Configure AWS Crendentials (CN)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CN_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CN_SECRET_ACCESS_KEY }}
          aws-region: cn-northwest-1

      - name: Publish Prebuilt to AWS (CN)
        uses: kungfu-trader/action-publish-prebuilt@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          bucket-staging: 'kungfu-prebuilt-staging'
          bucket-release: 'kungfu-prebuilt'

      - name: Publish to GitHub Packages
        run: npm publish
